#!/bin/sh

case $(uname -ms) in
  'Darwin x86_64')
    target=darwin-amd64
  ;;
  'Darwin arm64')
    target=darwin-arm64
  ;;
  'Linux aarch64' | 'Linux arm64')
    target=linux-arm64
  ;;
  'Linux x86_64' | *)
    target=linux-amd64
  ;;
esac

downloadURL=https://github.com/manas140/seam/releases/download/latest/seam-$target

printf '\033[1;32mINFO:\033[0;0m Downloading\n'

curl --fail --location --progress-bar --output "/tmp/seam" "$downloadURL" || exit 1

printf "\n\033[1;32mINFO:\033[0;0m Installing\n"

chmod +x /tmp/seam
mkdir ~/.local/bin/ 2>/dev/null
mv /tmp/seam ~/.local/bin/

case $(basename "$SHELL") in 
  "bash")
    if (!which seam 2>/dev/null); then
      printf "export PATH=\"\$PATH:$HOME/.local/bin/\"\n" >> ~/.bashrc
    fi
  ;;
  "zsh")
    if (! which seam 2>/dev/null); then
      printf "export PATH=\"\$PATH:$HOME/.local/bin/\"\n" >> ~/.zshrc
    fi
  ;;
  *)
    printf "\n\033[1;35mERROR:\033[0;0m shell not supported, please manually add directory to path (.bashrc or similar)\nexport PATH=\"\$PATH:~/.local/bin/\"\n"
  ;;
esac

printf "\n\033[1;32mTo get started run:\033[0;0m\n  exec $(basename $SHELL)\n  seam -h\n"
